FROM python:3.12-slim

WORKDIR /app

# Installation des dépendances système pour Airflow + crawl4ai
RUN apt-get update && apt-get install -y \
    wget curl gnupg ca-certificates build-essential \
    libglib2.0-0 libnss3 libnspr4 \
    libatk1.0-0 libatk-bridge2.0-0 libcups2 libdrm2 \
    libdbus-1-3 libxkbcommon0 libx11-6 libxcomposite1 \
    libxdamage1 libxext6 libxfixes3 libxrandr2 libgbm1 \
    libpango-1.0-0 libcairo2 libasound2 libatspi2.0-0 \
    xvfb \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Installation uv
ADD https://astral.sh/uv/install.sh /uv-installer.sh
RUN sh /uv-installer.sh && rm /uv-installer.sh

ENV PYTHONPATH="/app"


# Configuration uv
ENV PYTHONUNBUFFERED=1
ENV UV_CACHE_DIR=/tmp/uv-cache
ENV UV_LINK_MODE=copy

ENV PATH="/root/.local/bin:/app/.venv/bin:$PATH"


# Installation des dépendances Python
RUN uv venv

COPY requirements.txt .
RUN uv pip install -r requirements.txt

RUN test -f .venv/bin/airflow && echo "✅ airflow binary trouvé" || echo "❌ airflow binary manquant"

# Setup crawl4ai
RUN echo "🚀 Setup crawl4ai..." && \
    (crawl4ai-setup && echo "✅ crawl4ai-setup OK") || \
    echo "⚠️ crawl4ai-setup échoué"

RUN playwright install --with-deps chromium

# Copier le code
COPY . .

RUN mkdir -p /opt/airflow/logs && chmod -R 777 /opt/airflow

EXPOSE 8080
CMD ["bash", "-c", "Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 & airflow standalone"]