import re
import unicodedata
from difflib import SequenceMatcher
from typing import Tuple, List, Dict, Any, Set
from app.models import TailoredCVSchema


STOPWORDS: Set[str] = {
    "de", "d", "des", "du", "le", "la", "les", "un", "une", "et", "en", "pour", "par",
    "sur", "a", "au", "aux", "dans", "avec", "sous", "and", "of", "the", "in", "for",
    "with", "on", "to", "at"
}

ACTION_PREFIXES: Set[str] = {
    "conception", "developpement", "gestion", "mise en place", "creation", "architecture",
    "administration", "optimisation", "implementation", "pilotage", "design", "engineering",
    "analyse", "deploiement", "integration", "maintenance", "redaction", "structuration",
    "elaboration", "definition", "suivi"
}

TECHNICAL_SYNONYMS: Dict[str, List[str]] = {
    "modelisation de donnees": ["data modeling", "data model", "modelisation", "data models"],
    "modeles semantiques": ["semantic models", "semantic model", "modele semantique"],
    "dashboards decisionnels": ["dashboards", "dashboard", "power bi", "tableaux de bord", "tableau de bord"],
    "reporting analytique": ["reporting", "power bi", "analyses avancees", "analytics"],
    "pipelines multi sources": ["etl elt", "pipelines", "multi sources", "etl multi sources", "etl"],
    "apis rest": ["api rest", "fastapi", "rest api", "apis", "restful", "rest"],
    "api rest": ["apis rest", "fastapi", "rest api", "apis", "restful", "rest"],
    "rag": ["retrieval augmented generation", "systemes rag", "agents ia"],
    "apprentissage automatique": ["machine learning", "ml"],
    "apprentissage profond": ["deep learning", "dl"],
}


def _clean_str(s: str) -> str:
    """Normalizes string for comparison by lowercasing, stripping accents and punctuation."""
    if not s:
        return ""
    nfkd = unicodedata.normalize("NFKD", s)
    no_accents = "".join([c for c in nfkd if not unicodedata.combining(c)])
    cleaned = re.sub(r"[^\w\s]", " ", no_accents.lower())
    return re.sub(r"\s+", " ", cleaned).strip()


def _is_fuzzy_match(val: str, known_set: Set[str], threshold: float = 0.85) -> bool:
    """Checks if val is present in or closely matches any item in known_set."""
    clean_val = _clean_str(val)
    if not clean_val:
        return True

    for item in known_set:
        clean_item = _clean_str(item)
        if not clean_item:
            continue
        if clean_val == clean_item or clean_val in clean_item or clean_item in clean_val:
            return True
        if SequenceMatcher(None, clean_val, clean_item).ratio() >= threshold:
            return True
    return False


def _is_skill_supported(
    skill: str,
    known_skills: Set[str],
    profile_corpus: str,
    profile_tokens: Set[str],
    threshold: float = 0.82,
) -> bool:
    """
    Validates whether a skill generated by LLM is authentically grounded in the candidate profile.
    Checks direct fuzzy matching, corpus containment, action verb stripping, synonyms, and significant tokens.
    """
    c_skill = _clean_str(skill)
    if not c_skill:
        return True

    # 1. Direct match or fuzzy match against known skills set
    if _is_fuzzy_match(skill, known_skills, threshold=threshold):
        return True

    # 2. Substring containment in overall profile corpus
    if c_skill in profile_corpus:
        return True

    # 3. Action prefix stripping (e.g. "Conception d'APIs REST" -> "APIs REST")
    for act in ACTION_PREFIXES:
        if c_skill.startswith(act + " ") or c_skill.startswith(act + " d ") or c_skill.startswith(act + " de "):
            stripped = c_skill[len(act):].strip()
            words = stripped.split()
            while words and words[0] in STOPWORDS:
                words.pop(0)
            core = " ".join(words)
            if core and (core in profile_corpus or _is_fuzzy_match(core, known_skills, threshold=threshold)):
                return True
            if core in TECHNICAL_SYNONYMS:
                for syn in TECHNICAL_SYNONYMS[core]:
                    if syn in profile_corpus or syn in known_skills:
                        return True

    # 4. Synonym / translation mappings
    for k, syns in TECHNICAL_SYNONYMS.items():
        if c_skill == k or c_skill in k or k in c_skill:
            for syn in syns:
                if syn in profile_corpus or syn in known_skills or any(s in profile_tokens for s in syn.split()):
                    return True

    # 5. Check significant tokens (excluding stopwords and generic action words)
    significant_tokens = [
        w for w in c_skill.split()
        if w not in STOPWORDS and w not in ACTION_PREFIXES and len(w) > 2
    ]
    if significant_tokens:
        matched_tokens = sum(
            1 for w in significant_tokens
            if w in profile_tokens or any(SequenceMatcher(None, w, t).ratio() >= 0.88 for t in profile_tokens)
        )
        # If all tokens match, or at least 80% of tokens match for multi-word phrases
        if matched_tokens == len(significant_tokens) or (len(significant_tokens) >= 3 and matched_tokens / len(significant_tokens) >= 0.75):
            return True

    return False


def verify_cv_honesty(
    tailored: TailoredCVSchema,
    source_profile: Dict[str, Any],
) -> Tuple[bool, List[str]]:
    """
    Anti-hallucination guardrail for tailored CV generation.
    Verifies that no invented company, degree, or unsupported skill was injected by the LLM.
    """
    violations: List[str] = []

    # 1. Extraction of known companies
    known_companies: Set[str] = set()
    for exp in source_profile.get("experiences", []):
        comp = exp.get("company") or exp.get("entreprise")
        if comp:
            known_companies.add(str(comp).strip())

    for exp in tailored.experiences:
        if not _is_fuzzy_match(exp.company, known_companies):
            violations.append(
                f"Entreprise '{exp.company}' non trouvée dans les expériences du profil candidat."
            )

    # 2. Comprehensive extraction of candidate skills, technologies, missions, and text corpus
    known_skills: Set[str] = set()
    corpus_fragments: List[str] = []

    def _extract_text_fragments(data: Any) -> None:
        if isinstance(data, list):
            for item in data:
                _extract_text_fragments(item)
        elif isinstance(data, dict):
            for k, v in data.items():
                if isinstance(k, str) and not k.lower().endswith(("_skills", "skills", "langages")):
                    known_skills.add(k.strip())
                _extract_text_fragments(v)
        elif isinstance(data, str) and data.strip():
            known_skills.add(data.strip())
            corpus_fragments.append(data.strip())
            tokens = re.findall(r"[\w\.\+#\-]+", data)
            for token in tokens:
                if len(token) > 1:
                    known_skills.add(token.strip())

    # Ingest profile skills section
    _extract_text_fragments(source_profile.get("skills"))

    # Ingest profile experiences (stack, technologies, missions, description, role, achievements)
    for exp in source_profile.get("experiences", []) or []:
        for key in ["stack", "technologies", "missions", "missions_alt", "achievements"]:
            val = exp.get(key)
            if val:
                _extract_text_fragments(val)
        for text_key in ["description", "role", "title", "company"]:
            val = exp.get(text_key)
            if val and isinstance(val, str):
                corpus_fragments.append(val)
                known_skills.add(val.strip())

    # Ingest profile projects (stack, technologies, description, name, highlights)
    for proj in source_profile.get("projects", []) or []:
        for key in ["stack", "technologies", "highlights"]:
            val = proj.get(key)
            if val:
                _extract_text_fragments(val)
        for text_key in ["description", "name", "title"]:
            val = proj.get(text_key)
            if val and isinstance(val, str):
                corpus_fragments.append(val)
                known_skills.add(val.strip())

    # Ingest certifications and summaries
    for cert in source_profile.get("certifications", []) or []:
        if isinstance(cert, dict) and cert.get("name"):
            _extract_text_fragments(cert.get("name"))
        elif isinstance(cert, str):
            _extract_text_fragments(cert)

    for field in ["headline", "summary"]:
        val = source_profile.get(field)
        if val and isinstance(val, str):
            corpus_fragments.append(val)

    # Build normalized corpus and token index
    full_corpus_raw = " ".join(corpus_fragments)
    profile_corpus = _clean_str(full_corpus_raw)
    profile_tokens = set(re.findall(r"[\w\.\+#\-]+", profile_corpus))

    # Validate each skill in tailored prioritized skills
    for group in tailored.prioritized_skills:
        for skill in group.skills:
            if not _is_skill_supported(skill, known_skills, profile_corpus, profile_tokens):
                violations.append(
                    f"Compétence '{skill}' (catégorie '{group.category}') absente du profil candidat vérifié."
                )

    # 3. Extraction of education and degrees
    known_schools: Set[str] = set()
    known_degrees: Set[str] = set()
    for edu in source_profile.get("education", []) or []:
        school = edu.get("school") or edu.get("institution") or edu.get("ecole")
        if school:
            known_schools.add(str(school).strip())
        degree = edu.get("degree") or edu.get("diplome")
        if degree:
            known_degrees.add(str(degree).strip())

    for edu in tailored.education:
        school_match = _is_fuzzy_match(edu.institution, known_schools)
        degree_match = _is_fuzzy_match(edu.degree, known_degrees)
        if not (school_match or degree_match):
            violations.append(
                f"Formation '{edu.degree}' à '{edu.institution}' absente du cursus du profil candidat."
            )

    is_valid = len(violations) == 0
    return is_valid, violations
