name: Format and Lint

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  backend-lint:
    name: Backend - Format & Lint
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black isort flake8 flake8-black
        if [ -f backend/requirements.txt ]; then pip install -r backend/requirements.txt; fi
        
    - name: Format with Black
      run: |
        black backend/ --exclude "/(\.git|\.venv|venv|env)/"
        
    - name: Check imports with isort
      run: |
        isort --profile black backend/ --check
        
    - name: Lint with flake8
      run: |
        flake8 backend/ --max-line-length=88 --extend-ignore=E203,W503,E501 --select=C,E,F,W,B950 --exclude=.git,.venv,venv,env,__pycache__,dist,build

  frontend-lint:
    name: Frontend - Format & Lint
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'frontend/package-lock.json'
        
    - name: Install dependencies
      run: |
        cd frontend
        npm ci || npm install
        
    - name: Format with Prettier
      run: |
        cd frontend
        npx prettier --write .
        
    - name: Lint with ESLint
      run: |
        cd frontend
        npx eslint . --fix